dist: trusty

services:
  - postgresql

env:
  # Use test credentials for sequelize
  - NODE_ENV=test

sudo: required
before_install:
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn=1.5.1-1
addons:
  chrome: stable

language: node_js
node_js:
  - "9"

cache:
  yarn: true
  directories:
     - ./client/node_modules
     - ./server/node_modules

install:
  - yarn run client-server:install

script:
  # Use Chromium instead of Chrome.
  # - export CHROME_BIN=chromium-browser
  # Initialize database: create, migrate, seed
  - xvfb-run -a yarn run db
  # Run backend
  - xvfb-run -a yarn run server &
  # Run unit tests
  - xvfb-run -a yarn run client:unit
  # Run e2e tests
  - xvfb-run -a yarn run client:e2e
#   - sleep 3

after_script:
  # Stop backend
  - pkill node

notifications:
  email: false
